name: Deploy to Firebase Functions on server changes

'on':
  push:
    branches:
      - master
    paths:
      - server/**
  workflow_dispatch:

jobs:
  deploy_to_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd server && npm install
      - run: cd server/functions && npm install
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          PROJECT_PATH: ./server
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
